### ISSUE TITLE
volley通信終了後の処理に関して質問

### ISSUE THREAD

**Issue by shiratsu** [eure/traveling#3]
お世話になります

ひとつお聞かせください
まだ、自分が完全に理解してないところはあるのですが、
こちらのソースにある、MYRequest側で通信が終わり、jsonデータをパースした後、
fragment側に終わったことをどうやって通知してるのでしょうか。

すこし、その部分が腹に落ちてこなかったので、教えていただけますと幸いです

突然のご連絡すみません

よろしくお願いします。

**Comment by futabooo** [comment]
@shiratsu 
回答が遅くなってしまい申し訳ありません。
ご質問ありがとうございます。

コードと動作を確認したところ、jsonデータパース後にコールバックする処理が無いため、fragment側へパースが終わったことの通知がされていませんでした。

コールバックの追加含め、いくつか修正をしました。
https://github.com/eure/traveling/commit/898dda8659fcc8f44a29248b65276ab611f5d6cb

ご質問いただいた事でこのプロジェクトの間違いに気づきました！
本当にありがとうございます！

**Comment by shiratsu** [comment]
おお、了解です。ありがとうございます。
スッキリしました
